### ISSUE TITLE
HA unable to find sensors

### ISSUE THREAD

**Issue by enarik** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#25]
Hello! HA suddenly stopped updating the sensors about 48 hrs ago. Hoping you can help me find out why!

Core logs are below.

2020-10-20 17:17:39 WARNING (MainThread) [homeassistant.components.mobile_app.notify] Found duplicate device name iPad
2020-10-20 17:17:39 WARNING (MainThread) [homeassistant.components.mobile_app.notify] Found duplicate device name SM-G988U
2020-10-20 17:19:30 WARNING (MainThread) [homeassistant.components.mobile_app.notify] Found duplicate device name iPad
2020-10-20 17:19:30 WARNING (MainThread) [homeassistant.components.mobile_app.notify] Found duplicate device name SM-G988U
2020-10-20 17:19:30 WARNING (MainThread) [homeassistant.components.mobile_app.notify] Found duplicate device name iPad
2020-10-20 17:19:30 WARNING (MainThread) [homeassistant.components.mobile_app.notify] Found duplicate device name SM-G988U
2020-10-20 17:19:30 WARNING (MainThread) [homeassistant.components.mobile_app.notify] Found duplicate device name iPad
2020-10-20 17:19:30 WARNING (MainThread) [homeassistant.components.mobile_app.notify] Found duplicate device name SM-G988U
2020-10-20 17:19:30 WARNING (MainThread) [homeassistant.components.mobile_app.notify] Found duplicate device name iPad
2020-10-20 17:19:30 WARNING (MainThread) [homeassistant.components.mobile_app.notify] Found duplicate device name SM-G988U
2020-10-20 17:24:31 WARNING (MainThread) [homeassistant.components.mobile_app.notify] Found duplicate device name iPad
2020-10-20 17:24:31 WARNING (MainThread) [homeassistant.components.mobile_app.notify] Found duplicate device name SM-G988U
2020-10-20 17:24:31 WARNING (MainThread) [homeassistant.components.mobile_app.notify] Found duplicate device name iPad
2020-10-20 17:24:31 WARNING (MainThread) [homeassistant.components.mobile_app.notify] Found duplicate device name SM-G988U
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
Client error on /homeassistant/restart request 
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[17:25:30] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2020-10-20 17:25:51 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-10-20 17:25:51 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for smartthinq which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-10-20 17:26:01 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for wyzesense which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-10-20 17:26:02 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for govee_ble_hci which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-10-20 17:26:04 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up govee_ble_hci platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/govee_ble_hci/sensor.py", line 202, in setup_platform
    adapter = get_provider().get_adapter(int(config[CONF_HCI_DEVICE][-1]))
  File "/usr/local/lib/python3.8/site-packages/bleson/providers/linux/linux_provider.py", line 10, in get_adapter
    adapter.open()
  File "/usr/local/lib/python3.8/site-packages/bleson/providers/linux/linux_adapter.py", line 32, in open
    self._socket.bind((self.device_id,))
OSError: [Errno 19] No such device

**Comment by Thrilleratplay** [comment]
It was working then it stopped?  How long was it working before that?  Has anything changed? The errors suggest that the Bluetooth adapter cannot be connected to.  If you have an external Bluetooth adapter or have connected something new the HCI device number may have changed.

**Comment by enarik** [comment]
Hi @Thrilleratplay, it was working for a few months at least when it stopped. To my knowledge nothing has changed hardware or software wise around the time it stopped. Any addons that I had installed recently, I uninstalled to test.

No external BT adapters, using the onboard BT. No new USB or other connected devices either.

Thanks!

**Comment by Thrilleratplay** [comment]
That appears to the log when Home Assistant is first starting but the Bluetooth HCI is not found.  Try rebooting the physical device, some process may still be holding on to it.

**Comment by enarik** [comment]
I rebooted via the HA interface earlier today (host reboot, not restart) and just pulled the plug for a few minutes, same thing appears.

020-10-21 11:14:34 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up govee_ble_hci platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/govee_ble_hci/sensor.py", line 202, in setup_platform
    adapter = get_provider().get_adapter(int(config[CONF_HCI_DEVICE][-1]))
  File "/usr/local/lib/python3.8/site-packages/bleson/providers/linux/linux_provider.py", line 10, in get_adapter
    adapter.open()
  File "/usr/local/lib/python3.8/site-packages/bleson/providers/linux/linux_adapter.py", line 32, in open
    self._socket.bind((self.device_id,))
OSError: [Errno 19] No such device

**Comment by Thrilleratplay** [comment]
Do you have `hci_device` set in your config?

**Comment by enarik** [comment]
I do not have it set

**Comment by Thrilleratplay** [comment]
You wouldn't be using a Raspberry PI 3 would you?  The latest OS update apparently has a [Bluetooth issue](https://github.com/home-assistant/operating-system/issues/910)

**Comment by enarik** [comment]
Thank you! I am running a Pi 3. Same issue there. That is likely root cause, we can close out this issue then.

I appreciate the help! Sorry about the confusion on my side here.

**Comment by Thrilleratplay** [comment]
That is most likely your issue.  If nothing else changed there is no reason for the Bluetooth adapter not to be found.  No prob, it is just running down the list of things that can possibly go wrong...the OS breaking a fundamental protocol usually is not the first thing that is though of.
