### ISSUE TITLE
Integration crashes after a few hours with a bleson exception

### ISSUE THREAD

**Issue by BeckmaR** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#36]
Hey,

on my installation (RPi 3B+), integration v0.9.1, the sensor always stops working after a few hours. I found this in the logs:
```
2021-03-23 00:11:10 ERROR (HCISocketPoller) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/bleson/providers/linux/linux_adapter.py", line 59, in _socket_poller
    self._on_data(data)
  File "/usr/local/lib/python3.8/site-packages/bleson/providers/linux/linux_adapter.py", line 258, in _on_data
    hci_event_packet = parse_hci_event_packet(data[1:])
  File "/usr/local/lib/python3.8/site-packages/bleson/core/hci/type_converters.py", line 33, in parse_hci_event_packet
    subevtcode = struct.unpack("<B", data[2:3])[0]
struct.error: unpack requires a buffer of 1 bytes
2021-03-24 09:02:28 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
```
It looks like the final failing call (`struct.unpack`) would not be in your code, sadly, but maybe you can still find a way to catch this error and just restart something?

**Comment by Thrilleratplay** [comment]
@BeckmaR I believe a newer version of this library may catch the error itself.  From what I can gather in [this change](https://github.com/TheCellule/python-bleson/commit/e4f10bea80bb3a955b7f2d6ef7003a841a975191#diff-636367e788a7e7bd3a48667f705e311789434e10e03470405ada9e2b6d5edd29) an error like yours may occur when a BLE device that does not adhere to the spec is in range.  I updated the bleson version and released beta version `v0.9.2_beta_1` .  Could you test it and let me know if this solves your issue?

**Comment by BeckmaR** [comment]
@Thrilleratplay That was a quick one. I have updated the integration in my instance and will report back. Thanks!

**Comment by BeckmaR** [comment]
So now the sensor is still working after nearly 24 hours and the logs contain a bunch of these:
```Python
2021-03-26 08:55:31 ERROR (HCISocketPoller) [bleson] Exception ignored in HCISocketPoller
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/bleson/providers/linux/linux_adapter.py", line 60, in _socket_poller
    self._on_data(data)
  File "/usr/local/lib/python3.8/site-packages/bleson/providers/linux/linux_adapter.py", line 261, in _on_data
    hci_event_packet = parse_hci_event_packet(data[1:])
  File "/usr/local/lib/python3.8/site-packages/bleson/core/hci/type_converters.py", line 33, in parse_hci_event_packet
    subevtcode = struct.unpack("<B", data[2:3])[0]
struct.error: unpack requires a buffer of 1 bytes
```
I'd consider that a success. Many thanks for the uber-quick fix! Feel free to close this issue.

**Comment by Thrilleratplay** [comment]
That about of logging is annoying but glad it works.  Relased v0.92
